### ISSUE TITLE
Add 'deprecated in v5' classes file

### ISSUE THREAD

**Issue by coliff** [julien-deramond/bootstrap-deprecated-classes-extension#6]
This is a great extension - nice job on building this :-)

Not too important right now really, but could be nice to add a deprecated-in-v5 JSON file to track classes which are deprecated such as:

- `.carousel-dark` (https://getbootstrap.com/docs/5.3/components/carousel/#dark-variant)
- `.navbar-dark` (https://getbootstrap.com/docs/5.3/components/navbar/#color-schemes)
- `.dropdown-menu-dark` (https://getbootstrap.com/docs/5.3/components/dropdowns/)

**Comment by julien-deramond** [comment]
> This is a great extension - nice job on building this :-)

Thanks :-)

> Not too important right now really, but could be nice to add a deprecated-in-v5 JSON file to track classes which are deprecated such as:

Thanks for the suggestion! When I first created the extension, I aimed to make everything fully scripted. However, I can see how this would be really useful, especially for those working on v5 websites right now.

I don't think automating the detection of deprecated classes is feasible for a current version, so we can build the file manually instead. And if we miss anything, the community can always pitch in.

Feel free to kick things off by submitting a PR, and I'll jump in. Otherwise, I'll work on it myself as soon as possible :)

**Comment by coliff** [comment]
I cloned the repo and created a `bootstrap-5-deprecated-classes.json` but then got a bit stuck. :-)  Not too sure how the rest of it should work and I'm also unsure how about the UI should be for this.

I guess we'd add a Bootstrap 5 button but then it's not really too clear what the button refers to - if you wanted to see deprecated or unneeded classes for a Bootstrap 5 page you'd need to click both the Bootstrap 4 and Bootstrap 5 buttons... hmmm...

**Comment by julien-deramond** [comment]
We could start with a first version that includes the `bootstrap-5-deprecated-classes.json` and the Bootstrap 5 button. Thinking out loud, but right now, if I remember well, the buttons are already exclusive. In a separate PR/feature, I could try to make checkboxes instead.

In any case, feel free to go ahead and create a PR with the `bootstrap-5-deprecated-classes.json` file. It's already a great step to have gathered the deprecated classes for v5, and I'd be happy to jump in and help once it's up.
